version: '3.8'

services:
  # MongoDB 8 服務
  mongodb:
    image: mongo:8
    container_name: news_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password_2024
      MONGO_INITDB_DATABASE: news_analyze
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - news_network

  # Mongo Express 管理介面
  mongo-express:
    image: mongo-express:latest
    container_name: news_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_password_2024
      ME_CONFIG_MONGODB_URL: mongodb://root:root_password_2024@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin_password_2024
    depends_on:
      - mongodb
    networks:
      - news_network

  # PostgreSQL (保留以供切換)
  postgres:
    image: postgres:17-alpine
    container_name: news_analyze_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    profiles:
      - postgres

  # PgAdmin (保留以供切換)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: news_analyze_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - postgres

volumes:
  mongodb_data:
    driver: local
  postgres_data:
    driver: local

networks:
  news_network:
    driver: bridge
