"""Initial migration: create news table

Revision ID: 329301914add
Revises: 
Create Date: 2025-08-27 13:45:16.943945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329301914add'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 創建 news 資料表
    op.create_table('news',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('title', sa.String(500), nullable=False),
        sa.Column('content', sa.Text, nullable=True),
        sa.Column('url', sa.String(1000), nullable=True),
        sa.Column('source', sa.String(50), nullable=False),
        sa.Column('publish_time', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    # 創建唯一約束
    op.create_unique_constraint('uq_news_url', 'news', ['url'])
    
    # 創建索引以提升查詢效能
    op.create_index('idx_news_source', 'news', ['source'])
    op.create_index('idx_news_publish_time', 'news', ['publish_time'])
    op.create_index('idx_news_created_at', 'news', ['created_at'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 刪除索引
    op.drop_index('idx_news_created_at')
    op.drop_index('idx_news_publish_time') 
    op.drop_index('idx_news_source')
    
    # 刪除唯一約束
    op.drop_constraint('uq_news_url', 'news', type_='unique')
    
    # 刪除資料表
    op.drop_table('news')
    
    # ### end Alembic commands ###
