"""Initial migration: create news table

Revision ID: 329301914add
Revises: 
Create Date: 2025-08-27 13:45:16.943945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329301914add'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: 創建新的表結構
    op.execute('''
        CREATE TABLE news_new (
            pk INTEGER PRIMARY KEY AUTOINCREMENT,
            news_id VARCHAR(100) NOT NULL,
            news_source VARCHAR(50) NOT NULL,
            author VARCHAR(100),
            title TEXT,
            url TEXT,
            publish_time VARCHAR(50),
            create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_news_source_id UNIQUE (news_source, news_id)
        )
    ''')
    
    # Step 2: 遷移現有資料
    op.execute('''
        INSERT INTO news_new (news_id, news_source, author, title, url, publish_time, create_time)
        SELECT 
            CASE 
                WHEN id LIKE 'chinatimes_%' THEN SUBSTR(id, 12)
                WHEN id LIKE 'tvbs_%' THEN SUBSTR(id, 6)
                WHEN id LIKE 'ltn_%' THEN SUBSTR(id, 5)
                WHEN id LIKE 'setn_%' THEN SUBSTR(id, 6)
                ELSE id
            END as news_id,
            CASE 
                WHEN id LIKE 'chinatimes_%' THEN 'ChinaTimes'
                WHEN id LIKE 'tvbs_%' THEN 'TVBS'
                WHEN id LIKE 'ltn_%' THEN 'LTN'
                WHEN id LIKE 'setn_%' THEN 'SETN'
                ELSE COALESCE(news_name, 'Unknown')
            END as news_source,
            author,
            title,
            url,
            publish_time,
            create_time
        FROM news
        WHERE id IS NOT NULL
    ''')
    
    # Step 3: 刪除舊表並重命名新表
    op.drop_table('news')
    op.execute('ALTER TABLE news_new RENAME TO news')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: 創建舊的表結構
    op.execute('''
        CREATE TABLE news_old (
            id TEXT,
            news_name TEXT,
            author TEXT,
            title TEXT,
            url TEXT,
            publish_time TEXT,
            create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    
    # Step 2: 遷移資料回舊格式
    op.execute('''
        INSERT INTO news_old (id, news_name, author, title, url, publish_time, create_time)
        SELECT 
            CASE news_source
                WHEN 'ChinaTimes' THEN 'chinatimes_' || news_id
                WHEN 'TVBS' THEN 'tvbs_' || news_id  
                WHEN 'LTN' THEN 'ltn_' || news_id
                WHEN 'SETN' THEN 'setn_' || news_id
                ELSE news_id
            END as id,
            news_source as news_name,
            author,
            title,
            url,
            publish_time,
            create_time
        FROM news
    ''')
    
    # Step 3: 刪除新表並重命名舊表
    op.drop_table('news')
    op.execute('ALTER TABLE news_old RENAME TO news')
    
    # ### end Alembic commands ###
